#pragma once

enum kind { 
    KIND_EOI,
    KIND_LPAREN,
    KIND_RPAREN,
    KIND_ID,
    MAX_KIND
};

enum keyword {
    KEYWORD_DEFINE,
    KEYWORD_NAME,
    KEYWORD_DOMAIN,
    KEYWORD_REQUIREMENTS,
    KEYWORD_PREDICATES,
    KEYWORD_ACTION,
    KEYWORD_PARAMETERS,
    KEYWORD_PRECONDITION,
    KEYWORD_EFFECT,
    KEYWORD_AND,
    KEYWORD_OR,
    KEYWORD_NOT,
    KEYWORD_OBJECTS,
    KEYWORD_INIT,
    KEYWORD_GOAL,
    MAX_KEYWORD
};

extern const char *KIND_NAMES[MAX_KIND + 1];
extern const char *KEYWORD_NAMES[MAX_KEYWORD + 1];
